import json
import uuid
from datetime import datetime
from pathlib import Path

from app.core.config import get_settings
from app.core.models import Prediction


def generate_report(prediction: Prediction) -> Path:
    settings = get_settings()
    report_dir = Path(settings.media_dir) / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    out_path = report_dir / f"report_{prediction.id}_{uuid.uuid4().hex[:8]}.pdf"

    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Image as RLImage,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    doc = SimpleDocTemplate(str(out_path), pagesize=A4)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleX", parent=styles["Title"], fontSize=18, spaceAfter=12
    )
    h2 = styles["Heading2"]
    body = styles["BodyText"]

    story = [
        Paragraph("AI Medical Diagnostic System", title_style),
        Paragraph("Diagnostic Report", styles["Heading3"]),
        Spacer(1, 6 * mm),
        Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", body),
        Spacer(1, 4 * mm),
        Paragraph(f"Patient: {prediction.user.full_name if prediction.user else '—'}", body),
        Paragraph(f"Disease module: {prediction.disease}", body),
        Paragraph(f"Model version: {prediction.model_version}", body),
        Spacer(1, 6 * mm),
        Paragraph("Result", h2),
    ]

    probs = prediction.probabilities or {}
    rows = [
        ["Prediction", prediction.label],
        ["Confidence", f"{prediction.confidence:.2%}"],
    ]
    for label, value in probs.items():
        rows.append([f"P({label})", f"{value:.2%}"])
    if prediction.is_demo:
        rows.append(["Mode", "Demo (illustrative)"])

    table = Table(rows, colWidths=[60 * mm, 100 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 6 * mm))

    if prediction.heatmap_path and Path(prediction.heatmap_path).exists():
        story.append(Paragraph("Explanation (Grad-CAM overlay)", h2))
        story.append(RLImage(str(prediction.heatmap_path), width=80 * mm, height=80 * mm))
        story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("Explanation", h2))
    if prediction.explanation:
        story.append(Paragraph(json.dumps(prediction.explanation, indent=2, ensure_ascii=False), body))

    story.append(Spacer(1, 6 * mm))
    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by an AI decision-support prototype for "
            "screening and academic demonstration. It is not a certified diagnostic device and does not "
            "replace evaluation by a licensed medical professional.",
            body,
        )
    )

    doc.build(story)
    return out_path
